--- #YAML:1.0
name:                WWW-Bugzilla
version:             1.5
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Class::MethodMaker:            1.08
    Crypt::SSLeay:                 0.57
    Params::Validate:              0.88
    WWW::Mechanize:                1.3
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
